
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xllrulyirsebayaemlhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsbHJ1bHlpcnNlYmF5YWVtbGh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMDkxOTUsImV4cCI6MjA2MjY4NTE5NX0.OqBwi6W3rQwAZAhos_-7EqZgXXtFRoUUA2v1KWTKQy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
